FORMAT: 1A
HOST: http://api.jikan.me/v2

# Jikan

Jikan is an unofficial MyAnimeList PHP/REST API that covers the critical features which the official API lacks.

The old docs are available [https://jikan.me/old-docs](here)


Base URL: `http://api.jikan.me/`

Base URL (SSL): `https://api.jikan.me/`

# Rate Limiting
To maintain bandwidth, there's a rate-limiting of 2,000 requests per IP per day.

# Allowed HTTP(s) requests
<pre>
GET: All requests are done via GET
</pre>

# Response Headers
- 200 `OK` - the request was successful.
- 404 `Not Found` - resource was not found.
- 405 `Method Not Allowed` - requested method is not supported for resource.



## Anime [/anime/{id}/{request}/{parameter}]
A single anime object with all its details

### Anime [GET]

+ Parameters
    + id (required, Number, `1`) ... Returns the Anime details from that the ID
    + request (optional, String, `episodes`) ... More details such as characters, staff, episodes
    + parameter (optional, Number, `2`) ... Anime with more than 100 episodes are paginated, hence this parameter is required.

+ Response 200 (application/json)

        [
 
        ]