FORMAT: 1A
HOST: https://api.jikan.me/

# Jikan

Jikan is an unofficial MyAnimeList PHP/REST API that covers the critical features which the official API lacks.

The old docs are available [https://jikan.me/old-docs](here)


Base URL: `http://api.jikan.me/`

Base URL (SSL): `https://api.jikan.me/`

# Rate Limiting
To maintain bandwidth, there's a rate-limiting of 5,000 requests per IP per day and 2 concurrent requests per second.

Per Day: **2,000**

Concurrent: **2**/second

# Allowed HTTP(s) requests
<pre>
GET: All requests are done via GET
</pre>

# Response Headers
- 200 `OK` - the request was successful.
- 400 `Bad Request` - You've made an invalid request or to an invalid endpoint.
- 404 `Not Found` - The ID you requested doesn't exist
- 405 `Method Not Allowed` - requested method is not supported for resource.
- 429 `Too Many Requests` - You've either hit your daily limit, concurrent limit or Jikan has hit the rate limit from MyAnimeList


## Anime [/anime/{id}/{request}/{parameter}]
A single anime object with all its details

### Anime [GET]

+ Parameters
    + id (required, Number, `1`) ... Returns the Anime details from that the ID
    + request (optional, String, `episodes`) ... More details such as characters, staff, episodes
    + parameter (optional, Number, `2`) ... Anime with more than 100 episodes are paginated, hence this parameter is required.

+ Response 200 (application/json)

        [
 
        ]
        

## Manga [/manga/{id}/{request}]
A single manga object with all its details

### Anime [GET]

+ Parameters
    + id (required, Number, `1`) ... Returns the Character details from that the ID
    + request (optional, String, `characters`) ... More details such as characters
    
+ Response 200 (application/json)

        [
 
        ]
        
## Person [/person/{id}]
A single person object with all its details

### Anime [GET]

+ Parameters
    + id (required, Number, `1`) ... Returns the Person details from that the ID
    
+ Response 200 (application/json)

        [
 
        ]
        
## Character [/character/{id}]
A single character object with all its details

### Anime [GET]

+ Parameters
    + id (required, Number, `1`) ... Returns the Character details from that the ID
   
+ Response 200 (application/json)

        [
 
        ]