build: false
shallow_clone: false
platform:
  - x86
  - x64
clone_folder: c:\projects\jikan

environment:
  matrix:
    - PHP_VERSION: 7.1
    - PHP_VERSION: 7.2

cache:
  - '%APPDATA%\Composer'
  - c:\tools\php -> appveyor.yml
init:
  - SET PATH=C:\Program Files\OpenSSL;c:\tools\php;%PATH%
  - SET COMPOSER_NO_INTERACTION=1
  - SET PHP=1
  - SET ANSICON=121x90 (121x90)

install:
  - IF EXIST c:\tools\php (SET PHP=0)
  - ps: Set-Service wuauserv -StartupType Manual

  # Install PHP here
  - ps: appveyor-retry cinst --params '""/InstallDir:C:\tools\php""' --ignore-checksums -y php --version ((choco search php --exact --all-versions -r | select-string -pattern $env:PHP_VERSION | sort { [version]($_ -split '\|' | select -last 1) } -Descending | Select-Object -first 1) -replace '[php|]','')
  # - IF %PHP%==1 cinst -y OpenSSL.Light
  # - IF %PHP%==1 cinst -y php -version %PHP_VERSION%
  # - cd C:\tools\php71
  - cd c:\tools\php
  - IF %PHP%==1 copy php.ini-production php.ini
  - IF %PHP%==1 echo date.timezone="UTC" >> php.ini
  - IF %PHP%==1 echo memory_limit=1024M >> php.ini
  - IF %PHP%==1 echo extension_dir=ext >> php.ini
  - IF %PHP%==1 echo extension=php_curl.dll >> php.ini
  - IF %PHP%==1 echo extension=php_mbstring.dll >> php.ini
  - IF %PHP%==1 echo extension=php_openssl.dll >> php.ini
  - IF %PHP%==1 echo @php %%~dp0composer.phar %%* > composer.bat

  # Download
  - cd C:\tools
  - appveyor-retry appveyor DownloadFile https://getcomposer.org/composer.phar

before_test:
  - cd C:\projects\jikan
  - php C:\tools\composer.phar update --no-progress --profile --prefer-dist --no-scripts --no-interaction --no-suggest

test_script:
  - cd c:\projects\jikan
  - vendor\bin\phpunit --colors=always

on_success:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 success $env:WEBHOOK_URL_PASS
on_failure:
  - ps: Invoke-RestMethod https://raw.githubusercontent.com/k3rn31p4nic/appveyor-discord-webhook/master/send.ps1 -o send.ps1
  - ps: ./send.ps1 failure $env:WEBHOOK_URL_FAIL
